### ISSUE TITLE
[Bug] Rule not reporting calls inside top level objects

### ISSUE THREAD

**Issue by pallymore** [ericcornelissen/eslint-plugin-top#1080]
Hi - awesome plugin! thank you for making this.

I tried it out in our code base and noticed there might be a bug w/ top level side effect detection:

```ts
// ✅ This works - the plugin reports error here, awesome.
const foo = sideEffect();

// 🐞 - bug? this code also invokes sideEffect at the top level - but `@ericcornelissen/top/no-top-level-side-effects` ignores it. 
const FOO = {
  foo: sideEffect(),
};
```

**Comment by ericcornelissen** [comment]
> Hi - awesome plugin! thank you for making this.

:slightly_smiling_face: 


> I tried it out in our code base and noticed there might be a bug w/ top level side effect detection:

That looks like a bug too me. It seems to affect arrays too, but interestingly I did think to add a check for interpolated strings - anything else that we might be forgetting?

Are you interested in contributing a fix or not?

```javascript
// not reported
const x = {
  foo: sideEffect(),
};

// not reported
const y = [
  sideEffect(),
];

// reported
const z = `${sideEffect()}`;
```

**Comment by pallymore** [comment]
happy to take a look this weekend 😁 I've noticed the following is also considered a side effect violation:

```ts
function SomeReactComponent() { ... }

// ❌ this is reported as a top level side effect violation
SomeReactComponent.displayName = 'MyComponent';
```

is this expected?

**Comment by ericcornelissen** [comment]
> happy to take a look this weekend 😁

Cool, looking forward :slightly_smiling_face: 


> I've noticed the following is also considered a side effect violation:
> 
> ```ts
> function SomeReactComponent() { ... }
> 
> // ❌ this is reported as a top level side effect violation
> SomeReactComponent.displayName = 'MyComponent';
> ```
> 
> is this expected?

It is, but I will admit that it's a pattern that maybe deserves to be allowed via the plugin configuration. Please open a separate issue for it if you think it should be supported.
